# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(400, 0, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.uploadLabel = QtWidgets.QLabel(self.centralwidget)
        self.uploadLabel.setGeometry(QtCore.QRect(100, 50, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uploadLabel.setFont(font)
        self.uploadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uploadLabel.setObjectName("uploadLabel")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 300, 400, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.uploadProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.uploadProgressBar.setGeometry(QtCore.QRect(110, 170, 200, 30))
        self.uploadProgressBar.setProperty("value", 24)
        self.uploadProgressBar.setObjectName("uploadProgressBar")
        self.downloadLabel = QtWidgets.QLabel(self.centralwidget)
        self.downloadLabel.setGeometry(QtCore.QRect(100, 370, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.downloadLabel.setFont(font)
        self.downloadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.downloadLabel.setObjectName("downloadLabel")
        self.downloadProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.downloadProgressBar.setGeometry(QtCore.QRect(110, 470, 200, 30))
        self.downloadProgressBar.setProperty("value", 24)
        self.downloadProgressBar.setObjectName("downloadProgressBar")
        self.upPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.upPushButton.setGeometry(QtCore.QRect(240, 110, 100, 30))
        self.upPushButton.setObjectName("upPushButton")
        self.upSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.upSelectButton.setGeometry(QtCore.QRect(60, 110, 100, 30))
        self.upSelectButton.setObjectName("upSelectButton")
        self.downSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.downSelectButton.setGeometry(QtCore.QRect(60, 410, 100, 30))
        self.downSelectButton.setObjectName("downSelectButton")
        self.downPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.downPushButton.setGeometry(QtCore.QRect(240, 410, 100, 30))
        self.downPushButton.setObjectName("downPushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 25, 300, 500))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionupload = QtWidgets.QAction(MainWindow)
        self.actionupload.setObjectName("actionupload")
        self.actionstart_local = QtWidgets.QAction(MainWindow)
        self.actionstart_local.setObjectName("actionstart_local")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_VHV = QtWidgets.QAction(MainWindow)
        self.action_VHV.setObjectName("action_VHV")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setStatusTip("")
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_2.addAction(self.action_3)
        self.menu_3.addAction(self.action_VHV)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.actionExit)
        self.menu_4.addAction(self.action_5)
        self.menu_4.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FastAMT"))
        self.uploadLabel.setText(_translate("MainWindow", "等待选择文件"))
        self.downloadLabel.setText(_translate("MainWindow", "等待选择路径"))
        self.upPushButton.setText(_translate("MainWindow", "上传乐段"))
        self.upSelectButton.setText(_translate("MainWindow", "选择乐段"))
        self.downSelectButton.setText(_translate("MainWindow", "选择路径"))
        self.downPushButton.setText(_translate("MainWindow", "下载曲谱"))
        self.menu.setStatusTip(_translate("MainWindow", "开始工作"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_2.setStatusTip(_translate("MainWindow", "识谱菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "识谱"))
        self.menu_3.setStatusTip(_translate("MainWindow", "改谱菜单"))
        self.menu_3.setTitle(_translate("MainWindow", "改谱"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.actionupload.setText(_translate("MainWindow", "上传"))
        self.actionstart_local.setText(_translate("MainWindow", "start local VHV"))
        self.action_3.setText(_translate("MainWindow", "上传新文件"))
        self.action_3.setStatusTip(_translate("MainWindow", "点击以选取新的要识谱的mp3文件"))
        self.action_VHV.setText(_translate("MainWindow", "启动本地VHV服务器"))
        self.action_VHV.setStatusTip(_translate("MainWindow", "点击以在本地服务器上启动**kern曲谱编辑器"))
        self.action_4.setText(_translate("MainWindow", "打包"))
        self.action_5.setText(_translate("MainWindow", "关于"))
        self.action_5.setStatusTip(_translate("MainWindow", "点击以了解关于信息"))
        self.action_6.setText(_translate("MainWindow", "操作说明"))
        self.action_6.setStatusTip(_translate("MainWindow", "点击以学习如何使用本软件"))
        self.actionExit.setText(_translate("MainWindow", "退出"))

